database:
  host: 127.0.0.1
  port: 25432
  username: postgres
  password: yeework
  database_name: devices
  require_ssl: false
application:
  port: 3000
  host: 127.0.0.1
jwt_secret:
  secret_key: "secret"

